cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

brew "git"
brew "jq"
brew "neovim", args: ["HEAD"]
brew "ripgrep"
brew "starship"
brew "tmux"

cask "chromedriver"
cask "font-hack-nerd-font"
cask "hammerspoon"
cask "microsoft-edge"
cask "firefox"
cask "hot"
cask "stats"
cask "scapple"
cask "the-unarchiver"
cask "vlc"
cask "kindle"
cask "clipy"
cask "bitwarden"
cask "google-chrome"
cask "visual-studio-code"
cask "iterm2"
cask "notion"
cask "alfred"
cask "figma"
cask "postman"
cask "warp"
cask "kitty"
cask "wezterm"
cask "alacritty"
