# シェルプロンプトの間に空行を挿入します。
add_newline = true

# ファイルをスキャンする際のタイムアウト時間
scan_timeout = 10

# コマンド実行のタイムアウト時間(遅いという警告が表示されないように)
command_timeout = 1000

# 記号の設定
[character]
# success_symbol = "[](bold blue) [](bold blue)"
# success_symbol = "[](bold blue)"
success_symbol = "[](bold blue)"
# error_symbol = "[](bold blue) [](bold red)"
error_symbol = "[](bold blue)"

# conda環境の表示
[conda]
format = "[$symbol$environment](dimmed green) "
ignore_base = false  # base環境も表示させたい
